### ISSUE TITLE
gFlex on GRASS

### ISSUE THREAD

**Issue by marco97f** [awickert/gFlex#42]

**Comment by awickert** [comment]
Hi Marco,

Did the issue resolve itself / is this why you deleted the text and close the issue?

**Comment by marco97f** [comment]
Hi Andy,
no this is my mistake, but I sent you a message on researchgate where I
explained a bit more of my problem.
So, I tried to use r.flexure on GRASS but a message of error appears, when
I write g.extension r.flexure to install gFlex and also when I try to
install copying the url.
The error is: Cannot open URL:
http://wingrass.fsv.cvut.cz/grass78/x86_64/addons/grass-7.8.7dev/r.flexure.zip
Is this a problem with the packages repository of GRASS?
The gFlex code on Python (Spyder/Anaconda) works very well, but I'd like to
work with georeferenced rasters (I'm currently work on erosion unloading in
orogens)
Thanks a lot.

Marco


Il giorno sab 30 apr 2022 alle 09:26 Andy Wickert ***@***.***>
ha scritto:
